//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardStatu
    {
        public int CardStatusId { get; set; }
        public int CustomerId { get; set; }
        public string CardNumber { get; set; }
        public int CardType { get; set; }
        public string CardStatus { get; set; }
    
        public virtual CardType CardType1 { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
