//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CardStatus = new HashSet<CardStatu>();
            this.CustomerAssignMoneys = new HashSet<CustomerAssignMoney>();
            this.CustomerConsumingMoneys = new HashSet<CustomerConsumingMoney>();
            this.CustomerMonthlyPaids = new HashSet<CustomerMonthlyPaid>();
            this.Rewards = new HashSet<Reward>();
            this.CustomerPaidMoneys = new HashSet<CustomerPaidMoney>();
        }
    
        public int CustomerId { get; set; }
        public string Name { get; set; }
        public string Present_Address { get; set; }
        public string Parmanent_Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string CardNumber { get; set; }
        public Nullable<int> CardType { get; set; }
        public string CustomerStatus { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardStatu> CardStatus { get; set; }
        public virtual CardType CardType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAssignMoney> CustomerAssignMoneys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerConsumingMoney> CustomerConsumingMoneys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerMonthlyPaid> CustomerMonthlyPaids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reward> Rewards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPaidMoney> CustomerPaidMoneys { get; set; }
    }
}
