//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAssignMoney
    {
        public int ApplyingId { get; set; }
        public int CustomerId { get; set; }
        public int CardNo { get; set; }
        public int CardType { get; set; }
        public int Amount { get; set; }
        public int ApplyingMonth { get; set; }
        public string ApplyingStatus { get; set; }
        public string Message { get; set; }
    
        public virtual CardType CardType1 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual MonthTbl MonthTbl { get; set; }
    }
}
