//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPaidMoney
    {
        public int PaidId { get; set; }
        public int CustomerId { get; set; }
        public int Month { get; set; }
        public System.DateTime PaidDate { get; set; }
        public double PaidMoney { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MonthTbl MonthTbl { get; set; }
    }
}
