//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMonthlyPaid
    {
        public int MonthlyPaidId { get; set; }
        public int CustomerId { get; set; }
        public int CardNo { get; set; }
        public int Month { get; set; }
        public Nullable<double> ConsumeMoney { get; set; }
        public Nullable<double> PaidMoney { get; set; }
        public Nullable<double> ServiceCharge { get; set; }
        public Nullable<double> Fine { get; set; }
        public string PaidStatus { get; set; }
        public Nullable<double> ApplyingMoney { get; set; }
        public Nullable<double> CashBack { get; set; }
        public Nullable<double> TotalBill { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MonthTbl MonthTbl { get; set; }
    }
}
