//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CreditCardMSEntities : DbContext
    {
        public CreditCardMSEntities()
            : base("name=CreditCardMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardStatu> CardStatus { get; set; }
        public virtual DbSet<CardType> CardTypes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerAssignMoney> CustomerAssignMoneys { get; set; }
        public virtual DbSet<CustomerConsumingMoney> CustomerConsumingMoneys { get; set; }
        public virtual DbSet<CustomerMonthlyPaid> CustomerMonthlyPaids { get; set; }
        public virtual DbSet<CustomerPaidMoney> CustomerPaidMoneys { get; set; }
        public virtual DbSet<Reward> Rewards { get; set; }
        public virtual DbSet<MonthTbl> MonthTbls { get; set; }
    }
}
