//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonthTbl()
        {
            this.CustomerAssignMoneys = new HashSet<CustomerAssignMoney>();
            this.CustomerConsumingMoneys = new HashSet<CustomerConsumingMoney>();
            this.CustomerMonthlyPaids = new HashSet<CustomerMonthlyPaid>();
            this.CustomerPaidMoneys = new HashSet<CustomerPaidMoney>();
        }
    
        public int MonthId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ShortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAssignMoney> CustomerAssignMoneys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerConsumingMoney> CustomerConsumingMoneys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerMonthlyPaid> CustomerMonthlyPaids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPaidMoney> CustomerPaidMoneys { get; set; }
    }
}
